[project]
name = "app"
requires-python = ">=3.10"
dependencies = [
  "rdkit==2024.03.1",
  "numpy<2", # See: https://github.com/kuelumbus/rdkit-pypi/issues/102
  "sqlmodel~=0.0.22",
  "psycopg[binary]~=3.2.1"
]
version = "0.1.0"
